### PR TITLE
Supported VTK9

### PR DESCRIPTION
**Pull request by YonghaoZhao722**
# Fix VTK 9 Compatibility for macOS

## Problem

**MitoGraph cannot compile on modern macOS systems** due to VTK dependency issues:

- macOS Homebrew only provides **VTK 9**, not the required VTK 8.2.0
- Installing VTK 8.2.0 from source is complex and time-consuming
- VTK 9 has breaking API changes that cause compilation errors

## Error Example
```bash
./MitoGraph -xy 0.0645 -z 0.2 -path . -export_image_binary
dyld: Library not loaded: @rpath/libvtkDomainsChemistryOpenGL2-8.2.1.dylib
zsh: abort ./MitoGraph
```

## Solution

Add VTK 9 compatibility while maintaining VTK 8 support.

### Key Changes
1. **Updated CMakeLists.txt** - Support both VTK 8.x and 9.x
2. **Fixed API calls** - Updated 15 `FindPoint(x,y,z)` calls to VTK 9 format
3. **Replaced deprecated APIs** - `vtkLongArray` → `vtkTypeInt64Array`
4. **Removed deprecated keywords** - Cleaned up `register` usage

### Files Modified
- `CMakeLists.txt` - VTK version detection
- `MitoGraph.cxx` - API compatibility fixes
- `MitoThinning.cxx` - API compatibility fixes
- `ssThinning.cxx` - Deprecated keyword cleanup
- `tools/skell2img/includes.h` - Header updates

## Result

✅ **Easy Installation**: `brew install vtk` now works  
✅ **Same Functionality**: Identical output and performance  
✅ **Backward Compatible**: Still works with VTK 8.2.0+  
✅ **Clean Build**: No compilation errors or warnings  

**This resolves the critical macOS installation barrier while preserving all existing functionality.** 

For more detail, check **build_instructions_vtk9.md**.

### CODE REVIEW

**Comment by vianamp** [comment]
Thank you so much for this. I got VTK9 installed:

```
matheus.viana@OSXLTQQYV2L build % brew list vtk --versions  
vtk 9.4.2_1
```

Tried to build MitoGraph end and got this:

```
matheus.viana@OSXLTQQYV2L build % make
[ 25%] Building CXX object CMakeFiles/MitoGraph.dir/MitoGraph.cxx.o
In file included from /Users/matheus.viana/Documents/mitograph/MitoGraphVTK9/MitoGraph.cxx:18:
In file included from /Users/matheus.viana/Documents/mitograph/MitoGraphVTK9/ssThinning.h:4:
/Users/matheus.viana/Documents/mitograph/MitoGraphVTK9/includes.h:1:10: fatal error: 'list' file not found
    1 | #include <list>
      |          ^~~~~~
1 error generated.
make[2]: *** [CMakeFiles/MitoGraph.dir/MitoGraph.cxx.o] Error 1
make[1]: *** [CMakeFiles/MitoGraph.dir/all] Error 2
make: *** [all] Error 2
```

Would you provide a fix?

**Comment by YonghaoZhao722** [comment]
Hi,

The error 'list' file not found means your MacOS is missing the C++ standard library, which usually happens if the C++ compiler or Xcode Command Line Tools are not installed.

Please try running this in your terminal:
`xcode-select --install`

After installation, try building again.
If this works, I’ll update the build instructions in the README to include this step. I think it's not because the code, as I just include a standard library.

**Comment by vianamp** [comment]
It worked! For some reason I had to reinstall Xcode Command Line Tools.
